name: Github Workflow

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "File Name"
        required: True
        
      
        

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.event.inputs.filename}}"
      
      - name: Git clone our repository
        uses: actions/checkout@v2

      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with: 
          testFilePath: ./Testplans/S01_SimpleExample.jmx
          outputReportsFolder: reports/
          args: "-Jthreads=1 -Jcount=1 -Jrump=1"
      
      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
      
      - name: check
        run: ls && ls reports

#       - name: Generating Reports
#         uses: ./
#         with: 
#           testFilePath: -g Subscription.csv
#           outputReportsFolder: reports/
          


    
     
#       - name: Upload Results
#         uses: actions/upload-artifact@v2
#         with:
#           name: jmeter-results
#           path: Resultdir/








# jmeter -t TestPlan.jmx -Jthreads=10 -Jcount=50 -Jrumpup=5
