name: Github Workflow

on:
  push:
    branches:
      - main
        
      
        

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cache node modules
        id: myCacheStep
        uses: actions/cache@v2
        env:
          cache-name: cache-jmter-dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        if: steps.myCacheStep.outputs.cache-hit != 'true'
        uses: rbhadti94/apache-jmeter-action@v0.3.1      
      
      - name: Git clone our repository
        uses: actions/checkout@v2

      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with: 
          testFilePath: ./Testplans/S01_SimpleExample.jmx
          outputReportsFolder: reports/
          args: "-Jthreads=1 -Jcount=1 -Jrump=1"
      
      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/

#       - name: Generating Reports
#         uses: ./
#         with: 
#           testFilePath: -g Subscription.csv
#           outputReportsFolder: reports/
          


    
     
#       - name: Upload Results
#         uses: actions/upload-artifact@v2
#         with:
#           name: jmeter-results
#           path: Resultdir/








# jmeter -t TestPlan.jmx -Jthreads=10 -Jcount=50 -Jrumpup=5
